### ISSUE TITLE
Working with Azure PaaS MSSQL SSISDB

### ISSUE THREAD

**Issue by maverick126** [mmajcica/DeploySsis#7]
The package fails if the SSISDB catalog is hosted in Azure PaaS/Managed SQL server.   The package connects to master database which is results with $is.Catalogs.Count.    For Azure managed SQL servers, connection need to connect to SSISDB catalog.  This can be made into a parameter to avoid hard coding.

**Comment by mmajcica** [comment]
Hi @maverick126 

sorry for the late replay, I missed this message somehow.
I never worked with Azure Paas solution so I did not implement anything to directly support it.
If you know how to make it work, I'll be happy to accept a PR.

**Comment by maverick126** [comment]
Hi @mmajcica

Thank you for attending to this request.  I have put the changes in here
https://github.com/maverick126/DeploySsis.  The files that needs alteration
are:

1.  task/task.ps1  --
Line 13: added the line for the $initialcatalog param;
Line 78: inserted/passed the Initial catalog param in calling
the Get-SqlConnectionString


2. task/task.json

From line 78-86  added the block:
    {
      "groupName":"server",
      "name": "InitialCatalog",
      "type": "string",
      "label": "Initial Catalog",
      "required": false,
      "defaultValue": "SSISDB",
      "helpMarkDown": "Initial catalog for the SQL connection string."
    },

3.  README.md

Line 21:  Add the Initial Catalog line

**Comment by mmajcica** [comment]
By seeing your changes I do now understand better your issue.
Initially I was thinking to supply the Initial Catalog option for the user to be specified, then, by realizing that on SQL you can't change the name of it and it is always master, I decided to exclude it to make it simpler. (and I may have been wrong, considering not such an in-depth knowledge of SQL)
If this is necessary for the Azure, I'm more than happy to include it. 

Can you make a PR so that I can merge the code and deploy a new version of the extension?

**Comment by maverick126** [comment]
Hi @mmajcica

Thanks for that.  please see my PR for your review.

**Comment by mmajcica** [comment]
Solved in https://github.com/mmajcica/DeploySsis/pull/10
